on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  make:
    runs-on: macos-latest

    defaults:
      run:
        shell: zsh

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Dotfiles
        run: make all
